CREATE TABLE "anime" (
	"id" integer PRIMARY KEY NOT NULL,
	"romaji" text NOT NULL,
	"english" text,
	"synopsis" text,
	"cover_url" text,
	"cover_color" text,
	"banner_url" text,
	"format" text,
	"status" text,
	"episodes_count" integer,
	"duration" integer,
	"season" text,
	"season_year" integer,
	"score" real,
	"popularity" integer,
	"trailer_id" text,
	"trailer_site" text,
	"next_episode" integer,
	"next_airing_at" timestamp with time zone,
	"studio" text,
	"raw" jsonb,
	"synced_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "anime_genres" (
	"anime_id" integer NOT NULL,
	"genre_id" integer NOT NULL,
	CONSTRAINT "anime_genres_anime_id_genre_id_pk" PRIMARY KEY("anime_id","genre_id")
);
--> statement-breakpoint
CREATE TABLE "comments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "comments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" uuid NOT NULL,
	"anime_id" integer NOT NULL,
	"episode_number" integer,
	"body" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "devices" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "episodes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "episodes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"anime_id" integer NOT NULL,
	"number" integer NOT NULL,
	"title" text,
	"synopsis" text,
	"thumbnail_url" text,
	"duration_seconds" integer,
	"air_date" timestamp with time zone,
	"video_asset_id" integer
);
--> statement-breakpoint
CREATE TABLE "genres" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "genres_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	CONSTRAINT "genres_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "library_entries" (
	"device_id" uuid NOT NULL,
	"anime_id" integer NOT NULL,
	"list" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "library_entries_device_id_anime_id_list_pk" PRIMARY KEY("device_id","anime_id","list")
);
--> statement-breakpoint
CREATE TABLE "ratings" (
	"device_id" uuid NOT NULL,
	"anime_id" integer NOT NULL,
	"value" smallint NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ratings_device_id_anime_id_pk" PRIMARY KEY("device_id","anime_id")
);
--> statement-breakpoint
CREATE TABLE "row_items" (
	"row_id" integer NOT NULL,
	"anime_id" integer NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "row_items_row_id_anime_id_pk" PRIMARY KEY("row_id","anime_id")
);
--> statement-breakpoint
CREATE TABLE "rows" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rows_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" text NOT NULL,
	"title" text NOT NULL,
	"subtitle" text,
	"kind" text DEFAULT 'curated' NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "rows_key_unique" UNIQUE("key")
);
--> statement-breakpoint
CREATE TABLE "video_assets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "video_assets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"provider" text NOT NULL,
	"playback_id" text,
	"status" text DEFAULT 'ready' NOT NULL,
	"duration_seconds" integer,
	"aspect_ratio" text
);
--> statement-breakpoint
CREATE TABLE "watch_progress" (
	"device_id" uuid NOT NULL,
	"episode_id" integer NOT NULL,
	"position_seconds" integer DEFAULT 0 NOT NULL,
	"duration_seconds" integer DEFAULT 0 NOT NULL,
	"completed" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "watch_progress_device_id_episode_id_pk" PRIMARY KEY("device_id","episode_id")
);
--> statement-breakpoint
ALTER TABLE "anime_genres" ADD CONSTRAINT "anime_genres_anime_id_anime_id_fk" FOREIGN KEY ("anime_id") REFERENCES "public"."anime"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "anime_genres" ADD CONSTRAINT "anime_genres_genre_id_genres_id_fk" FOREIGN KEY ("genre_id") REFERENCES "public"."genres"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comments" ADD CONSTRAINT "comments_device_id_devices_id_fk" FOREIGN KEY ("device_id") REFERENCES "public"."devices"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comments" ADD CONSTRAINT "comments_anime_id_anime_id_fk" FOREIGN KEY ("anime_id") REFERENCES "public"."anime"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "episodes" ADD CONSTRAINT "episodes_anime_id_anime_id_fk" FOREIGN KEY ("anime_id") REFERENCES "public"."anime"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "library_entries" ADD CONSTRAINT "library_entries_device_id_devices_id_fk" FOREIGN KEY ("device_id") REFERENCES "public"."devices"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "library_entries" ADD CONSTRAINT "library_entries_anime_id_anime_id_fk" FOREIGN KEY ("anime_id") REFERENCES "public"."anime"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ratings" ADD CONSTRAINT "ratings_device_id_devices_id_fk" FOREIGN KEY ("device_id") REFERENCES "public"."devices"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ratings" ADD CONSTRAINT "ratings_anime_id_anime_id_fk" FOREIGN KEY ("anime_id") REFERENCES "public"."anime"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "row_items" ADD CONSTRAINT "row_items_row_id_rows_id_fk" FOREIGN KEY ("row_id") REFERENCES "public"."rows"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "row_items" ADD CONSTRAINT "row_items_anime_id_anime_id_fk" FOREIGN KEY ("anime_id") REFERENCES "public"."anime"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "watch_progress" ADD CONSTRAINT "watch_progress_device_id_devices_id_fk" FOREIGN KEY ("device_id") REFERENCES "public"."devices"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "watch_progress" ADD CONSTRAINT "watch_progress_episode_id_episodes_id_fk" FOREIGN KEY ("episode_id") REFERENCES "public"."episodes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "anime_status_idx" ON "anime" USING btree ("status");--> statement-breakpoint
CREATE INDEX "anime_season_year_idx" ON "anime" USING btree ("season_year");--> statement-breakpoint
CREATE INDEX "anime_popularity_idx" ON "anime" USING btree ("popularity");--> statement-breakpoint
CREATE INDEX "anime_genres_genre_idx" ON "anime_genres" USING btree ("genre_id");--> statement-breakpoint
CREATE INDEX "comments_anime_idx" ON "comments" USING btree ("anime_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "episodes_anime_number_idx" ON "episodes" USING btree ("anime_id","number");--> statement-breakpoint
CREATE INDEX "episodes_anime_idx" ON "episodes" USING btree ("anime_id");--> statement-breakpoint
CREATE UNIQUE INDEX "genres_name_idx" ON "genres" USING btree ("name");--> statement-breakpoint
CREATE INDEX "library_entries_device_idx" ON "library_entries" USING btree ("device_id");--> statement-breakpoint
CREATE INDEX "rows_position_idx" ON "rows" USING btree ("position");--> statement-breakpoint
CREATE INDEX "watch_progress_device_idx" ON "watch_progress" USING btree ("device_id","updated_at");